stages:

  prepare_base_model:
    cmd: python src/dogCatClassification/pipeline/step_2_prepare_base_model.py
    deps:
    - src/dogCatClassification/pipeline/step_2_prepare_base_model.py
    - config/config.yaml

    params:
    - IMAGE_SIZE
    - INCLUDE_TOP
    - CLASSES
    - WEIGHTS
    - LEARNING_RATE
    - OUTPTUT_ACTIVATION_FUNCTION
    - METRICS
    outs:
    - artifacts/prepare_base_model


  training:
    cmd: python src/dogCatClassification/pipeline/step_3_training.py
    deps:
    - src/dogCatClassification/pipeline/step_3_training.py
    - config/config.yaml
    - data/
    - artifacts/prepare_base_model
    params:
    - IMAGE_SIZE
    - EPOCHS
    - BATCH_SIZE
    - AUGMENTATION
    outs:
    - artifacts/training/model.h5

  evaluation:
    cmd: python src/dogCatClassification/pipeline/step_4_evaluation.py
    deps:
    - src/dogCatClassification/pipeline/step_4_evaluation.py
    - config/config.yaml
    - data/
    - artifacts/training/model.h5
    params:
    - IMAGE_SIZE
    - BATCH_SIZE
    metrics:
    - metrics.json:
        cache: false
