name: Model Training and Evaluation Pipeline

on:
  push:
    branches:
      - dev
    paths:
      - data.dvc
  pull_request:
    branches:
      - dev

jobs:
        build:
          runs-on: ubuntu-latest

          steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Requirements
              run: pip install -r requirements.txt

            - name: Configure DVC remote
              run: dvc remote add -f origin https://dagshub.com/fanerami/dog_cat_classification_v3.dvc

            - name: Pull latest data with DVC
              run: dvc pull
